/* CRM ilk şema - referans (canlıda CrmSchemaU migrasyon 1 ile de uygulanır)
   Veritabanı: ASYA_ENTEGRE
   Collation: SQL_Latin1_General_CP1_CI_AS (metin kolonları)
*/

SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.CRM_SCHEMA_GECMIS', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_SCHEMA_GECMIS (
    SURUM_NO            INT NOT NULL CONSTRAINT PK_CRM_SCHEMA_GECMIS PRIMARY KEY,
    UYGULANMA_UTC       DATETIME2(3) NOT NULL CONSTRAINT DF_CRM_SCH_UTC DEFAULT (SYSUTCDATETIME()),
    ACIKLAMA            VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
  );
END;
GO

IF OBJECT_ID(N'dbo.CRM_AKTIVITE', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_AKTIVITE (
    AKTIVITE_ID              BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_AKTIVITE PRIMARY KEY,
    TIP                      VARCHAR(30)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    KONU                     VARCHAR(250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    ACIKLAMA                 VARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CARI_KOD                 VARCHAR(50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    AKTIVITE_TARIHI          DATETIME2(3) NOT NULL,
    DURUM                    VARCHAR(20)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
                              CONSTRAINT DF_CRM_AKT_DURUM DEFAULT (N'ACIK'),
    OLUSTURAN_KULLANICI_ID   INT NULL,
    OLUSTURMA_UTC            DATETIME2(3) NOT NULL CONSTRAINT DF_CRM_AKT_OLUSTR DEFAULT (SYSUTCDATETIME()),
    GUNCELLEME_UTC           DATETIME2(3) NULL,
    CONSTRAINT CK_CRM_AKT_TIP CHECK (TIP IN (N'CALL', N'MEETING', N'EMAIL', N'TASK', N'NOTE', N'OTHER')),
    CONSTRAINT CK_CRM_AKT_DURUM CHECK (DURUM IN (N'ACIK', N'TAMAMLANDI', N'IPTAL'))
  );
  CREATE INDEX IX_CRM_AKT_CARI ON dbo.CRM_AKTIVITE (CARI_KOD);
  CREATE INDEX IX_CRM_AKT_TAR ON dbo.CRM_AKTIVITE (AKTIVITE_TARIHI);
  CREATE INDEX IX_CRM_AKT_TIP_DURUM ON dbo.CRM_AKTIVITE (TIP, DURUM);
END;
GO

IF OBJECT_ID(N'dbo.CRM_GOREV', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_GOREV (
    GOREV_ID                 BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_GOREV PRIMARY KEY,
    AKTIVITE_ID              BIGINT NOT NULL,
    ATANAN_KULLANICI_ID      INT NULL,
    BITIS_TARIHI             DATETIME2(3) NULL,
    ONCELIK                  VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
                              CONSTRAINT DF_CRM_GRV_ONCELIK DEFAULT (N'NORMAL'),
    TAMAMLANDI               BIT NOT NULL CONSTRAINT DF_CRM_GRV_TAM DEFAULT (0),
    TAMAMLANMA_UTC           DATETIME2(3) NULL,
    CONSTRAINT UQ_CRM_GOREV_AKT UNIQUE (AKTIVITE_ID),
    CONSTRAINT FK_CRM_GOREV_AKT FOREIGN KEY (AKTIVITE_ID) REFERENCES dbo.CRM_AKTIVITE (AKTIVITE_ID) ON DELETE CASCADE,
    CONSTRAINT CK_CRM_GRV_ONCELIK CHECK (ONCELIK IN (N'DUSUK', N'NORMAL', N'YUKSEK', N'ACIL'))
  );
  CREATE INDEX IX_CRM_GRV_ATANAN ON dbo.CRM_GOREV (ATANAN_KULLANICI_ID, TAMAMLANDI);
  CREATE INDEX IX_CRM_GRV_BITIS ON dbo.CRM_GOREV (BITIS_TARIHI);
END;
GO

/* Form / yetki kayıtları (tablolar mevcut ise) */
IF OBJECT_ID(N'dbo.FormName', N'U') IS NOT NULL
BEGIN
  INSERT INTO dbo.FormName (FormName, FormCaption)
  SELECT v.FN, v.FC FROM (VALUES
    (N'CrmYeniAktivite', N'CRM - Yeni Aktivite'),
    (N'CrmYeniGorev',    N'CRM - Yeni Görev')
  ) AS v(FN, FC)
  WHERE NOT EXISTS (SELECT 1 FROM dbo.FormName f WHERE f.FormName = v.FN);
END;
GO

IF OBJECT_ID(N'dbo.YETKI', N'U') IS NOT NULL AND OBJECT_ID(N'dbo.KULLANICIGRUP', N'U') IS NOT NULL
BEGIN
  INSERT INTO dbo.YETKI (KullaniciGrupID, FormName, Gor, Sil, Degistir, Kaydet)
  SELECT g.KullaniciGrupID, N'CrmYeniAktivite', 1, 1, 1, 1
  FROM dbo.KULLANICIGRUP g
  WHERE NOT EXISTS (
    SELECT 1 FROM dbo.YETKI y WHERE y.KullaniciGrupID = g.KullaniciGrupID AND y.FormName = N'CrmYeniAktivite');

  INSERT INTO dbo.YETKI (KullaniciGrupID, FormName, Gor, Sil, Degistir, Kaydet)
  SELECT g.KullaniciGrupID, N'CrmYeniGorev', 1, 1, 1, 1
  FROM dbo.KULLANICIGRUP g
  WHERE NOT EXISTS (
    SELECT 1 FROM dbo.YETKI y WHERE y.KullaniciGrupID = g.KullaniciGrupID AND y.FormName = N'CrmYeniGorev');
END;
GO
