/* CRM surum 4 - Teklif baslik ve satir (canlida CrmSchemaU migrasyon 4 ile uygulanir) */

IF OBJECT_ID(N'dbo.CRM_TEKLIF', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_TEKLIF (
    TEKLIF_ID               BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_TEKLIF PRIMARY KEY,
    CARI_KOD                VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    BASLIK                  VARCHAR(250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    TEKLIF_TARIHI           DATETIME2(3) NOT NULL CONSTRAINT DF_CRM_TKL_TAR DEFAULT (SYSUTCDATETIME()),
    GECERLILIK_TARIHI       DATETIME2(3) NULL,
    DURUM                   VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT DF_CRM_TKL_DUR DEFAULT (N'TASLAK'),
    ACIKLAMA                VARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TOPLAM_NET              DECIMAL(18,4) NOT NULL CONSTRAINT DF_CRM_TKL_TOP DEFAULT (0),
    OLUSTURAN_KULLANICI_ID  INT NULL,
    OLUSTURMA_UTC           DATETIME2(3) NOT NULL CONSTRAINT DF_CRM_TKL_OLU DEFAULT (SYSUTCDATETIME()),
    GUNCELLEME_UTC          DATETIME2(3) NULL
  );
  CREATE INDEX IX_CRM_TKL_CARI ON dbo.CRM_TEKLIF (CARI_KOD);
  CREATE INDEX IX_CRM_TKL_TAR ON dbo.CRM_TEKLIF (TEKLIF_TARIHI);
END;
GO

IF OBJECT_ID(N'dbo.CRM_TEKLIF_SATIR', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_TEKLIF_SATIR (
    SATIR_ID    BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_TEKLIF_SATIR PRIMARY KEY,
    TEKLIF_ID   BIGINT NOT NULL,
    SIRA        INT NOT NULL CONSTRAINT DF_CRM_TKS_SIRA DEFAULT (0),
    STOK_KOD    VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    STOK_ADI    VARCHAR(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MIKTAR      DECIMAL(18,4) NOT NULL,
    BIRIM       VARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    BIRIM_FIYAT DECIMAL(18,4) NOT NULL,
    TUTAR       DECIMAL(18,4) NOT NULL,
    CONSTRAINT FK_CRM_TKS_TKL FOREIGN KEY (TEKLIF_ID) REFERENCES dbo.CRM_TEKLIF (TEKLIF_ID) ON DELETE CASCADE
  );
  CREATE INDEX IX_CRM_TKS_TKL ON dbo.CRM_TEKLIF_SATIR (TEKLIF_ID, SIRA);
END;
GO
