/*
  CRM surum 11 - Potansiyel musteri (referans script).
  Canlida CrmSchemaU.CrmSchemaApplyMigration11 + CRM_SCHEMA_TARGET_VERSION = 11 ile otomatik uygulanir.
  Veritabani: ASYA_ENTEGRE
*/

SET NOCOUNT ON;

/* --- CRM_POTANSIYEL_DURUM --- */
IF OBJECT_ID(N'dbo.CRM_POTANSIYEL_DURUM', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_POTANSIYEL_DURUM (
    POTANSIYEL_DURUM_ID   BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_POTANSIYEL_DURUM PRIMARY KEY,
    KOD                   VARCHAR(30)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    ACIKLAMA              VARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    AKTIF                 BIT NOT NULL CONSTRAINT DF_CRM_POTDUR_AKTIF DEFAULT (1),
    SIRA                  INT NOT NULL CONSTRAINT DF_CRM_POTDUR_SIRA DEFAULT (0),
    CONSTRAINT UQ_CRM_POTANSIYEL_DURUM_KOD UNIQUE (KOD)
  );
  CREATE INDEX IX_CRM_POTDUR_AKT_SIRA ON dbo.CRM_POTANSIYEL_DURUM (AKTIF, SIRA);
END;
GO

/* Tohum durumlar */
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'YENI')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'YENI', N'Yeni / Ilk kontak', 1, 10);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'ILETISIM')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'ILETISIM', N'Iletisim suruyor', 1, 20);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'TEKLIF_ASAMASI')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'TEKLIF_ASAMASI', N'Teklif asamasinda', 1, 30);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'MUZAKERE')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'MUZAKERE', N'Muzakere / pazarlik', 1, 40);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'KAZANILDI')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'KAZANILDI', N'Kazanildi', 1, 50);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'KAYBEDILDI')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'KAYBEDILDI', N'Kaybedildi / uygun degil', 1, 60);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'NETSIS_BAGLI')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'NETSIS_BAGLI', N'Netsis cari ile baglandi', 1, 70);
IF NOT EXISTS (SELECT 1 FROM dbo.CRM_POTANSIYEL_DURUM WHERE KOD = N'PASIF')
  INSERT INTO dbo.CRM_POTANSIYEL_DURUM (KOD, ACIKLAMA, AKTIF, SIRA) VALUES (N'PASIF', N'Pasif / takip disi', 1, 90);
GO

/* --- CRM_POTANSIYEL_MUSTERI --- */
IF OBJECT_ID(N'dbo.CRM_POTANSIYEL_MUSTERI', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.CRM_POTANSIYEL_MUSTERI (
    POTANSIYEL_ID           BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CRM_POTANSIYEL_MUSTERI PRIMARY KEY,
    FIRMA_UNVAN             VARCHAR(250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    KISA_AD                 VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MUSTERI_TIPI            VARCHAR(20)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT DF_CRM_POT_TIP DEFAULT (N'KURUMSAL'),
    VERGI_DAIRESI           VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    VERGI_NO                VARCHAR(20)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TC_KIMLIK_NO            VARCHAR(11)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MERSIS_NO               VARCHAR(30)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    NETSIS_CARI_KOD         VARCHAR(50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    NETSIS_BAGLANTI_UTC     DATETIME2(3) NULL,
    ULKE                    VARCHAR(80)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    IL                      VARCHAR(80)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ILCE                    VARCHAR(80)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    POSTA_KODU              VARCHAR(15)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ADRES                   VARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TELEFON_SABIT           VARCHAR(40)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TELEFON_CEPTEL          VARCHAR(40)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    TELEFON2                VARCHAR(40)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FAKS                    VARCHAR(40)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    EPOSTA                  VARCHAR(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    WEB                     VARCHAR(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    YETKILI_AD_SOYAD        VARCHAR(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    YETKILI_UNVAN           VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    YETKILI_EPOSTA          VARCHAR(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    YETKILI_TEL             VARCHAR(40)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MUHASEBE_YETKILI_AD     VARCHAR(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MUHASEBE_TEL            VARCHAR(40)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    MUHASEBE_EPOSTA         VARCHAR(120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    SEKTOR                  VARCHAR(150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    FAALIYET_KONUSU         VARCHAR(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CALISAN_SAYISI          INT NULL,
    TAHMINI_YILLIK_CIRO     DECIMAL(18,2) NULL,
    PARA_BIRIMI             VARCHAR(10)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT DF_CRM_POT_PB DEFAULT (N'TRY'),
    KAYNAK                  VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    POTANSIYEL_DURUM_ID     BIGINT NOT NULL,
    ILK_ILETISIM_TARIHI     DATE NULL,
    SON_TAKIP_TARIHI        DATE NULL,
    SONRAKI_AKSYON_TARIHI   DATE NULL,
    NOTLAR                  VARCHAR(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    OLUSTURAN_KULLANICI_ID  INT NULL,
    OLUSTURMA_UTC           DATETIME2(3) NOT NULL CONSTRAINT DF_CRM_POT_OLU DEFAULT (SYSUTCDATETIME()),
    GUNCELLEME_UTC          DATETIME2(3) NULL,
    CONSTRAINT FK_CRM_POT_POTDUR FOREIGN KEY (POTANSIYEL_DURUM_ID) REFERENCES dbo.CRM_POTANSIYEL_DURUM (POTANSIYEL_DURUM_ID),
    CONSTRAINT CK_CRM_POT_MUSTIP CHECK (MUSTERI_TIPI IN (N'KURUMSAL', N'BIREYSEL'))
  );
  CREATE INDEX IX_CRM_POT_NETSIS ON dbo.CRM_POTANSIYEL_MUSTERI (NETSIS_CARI_KOD);
  CREATE INDEX IX_CRM_POT_DURUM ON dbo.CRM_POTANSIYEL_MUSTERI (POTANSIYEL_DURUM_ID);
  CREATE INDEX IX_CRM_POT_UNVAN ON dbo.CRM_POTANSIYEL_MUSTERI (FIRMA_UNVAN);
END;
GO

/* FormName / YETKI: migrasyon kodu CrmSchemaApplyMigration11 ile eklenir. */

IF NOT EXISTS (SELECT 1 FROM dbo.CRM_SCHEMA_GECMIS WHERE SURUM_NO = 11)
  INSERT INTO dbo.CRM_SCHEMA_GECMIS (SURUM_NO, ACIKLAMA) VALUES (11, N'CRM potansiyel musteri ve Netsis cari baglanti');
GO
