/*
  CRM surum 15 - Rota GPSX/GPSY, PARAMETRE varsayilan konum, durak-gorev iliskisi.
  Veritabani: ASYA_ENTEGRE
  Idempotent: tekrar calistirilabilir.
*/

SET NOCOUNT ON;

/* --- PARAMETRE: rota baslangic varsayilan GPS --- */
IF OBJECT_ID(N'dbo.PARAMETRE', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.PARAMETRE', 'GPSX') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD GPSX DECIMAL(18,8) NULL;
  IF COL_LENGTH('dbo.PARAMETRE', 'GPSY') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD GPSY DECIMAL(18,8) NULL;
END;
GO

/* --- CRM_ROTA_PLAN: merkez / baslangic GPS --- */
IF OBJECT_ID(N'dbo.CRM_ROTA_PLAN', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'GPSX') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD GPSX DECIMAL(18,8) NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'GPSY') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD GPSY DECIMAL(18,8) NULL;

  UPDATE dbo.CRM_ROTA_PLAN
  SET GPSX = BASLANGIC_ENLEM, GPSY = BASLANGIC_BOYLAM
  WHERE GPSX IS NULL AND BASLANGIC_ENLEM IS NOT NULL;

  UPDATE dbo.CRM_ROTA_PLAN
  SET GPSY = BASLANGIC_BOYLAM
  WHERE GPSY IS NULL AND BASLANGIC_BOYLAM IS NOT NULL;
END;
GO

/* --- CRM_ROTA_PLAN_DURAK: gorev iliskisi --- */
IF OBJECT_ID(N'dbo.CRM_ROTA_PLAN_DURAK', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN_DURAK', 'GOREV_ID') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK ADD GOREV_ID BIGINT NULL;

  IF COL_LENGTH('dbo.CRM_ROTA_PLAN_DURAK', 'GPSX') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK ADD GPSX DECIMAL(18,8) NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN_DURAK', 'GPSY') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK ADD GPSY DECIMAL(18,8) NULL;

  UPDATE dbo.CRM_ROTA_PLAN_DURAK
  SET GPSX = GPS_ENLEM, GPSY = GPS_BOYLAM
  WHERE GPSX IS NULL AND GPS_ENLEM IS NOT NULL;

  UPDATE dbo.CRM_ROTA_PLAN_DURAK
  SET GPSY = GPS_BOYLAM
  WHERE GPSY IS NULL AND GPS_BOYLAM IS NOT NULL;

  IF NOT EXISTS (
    SELECT 1 FROM sys.foreign_keys
    WHERE name = N'FK_CRM_ROTA_DURAK_GOREV'
      AND parent_object_id = OBJECT_ID(N'dbo.CRM_ROTA_PLAN_DURAK'))
  BEGIN
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK WITH CHECK
      ADD CONSTRAINT FK_CRM_ROTA_DURAK_GOREV
      FOREIGN KEY (GOREV_ID) REFERENCES dbo.CRM_GOREV (GOREV_ID) ON DELETE SET NULL;
  END;

  IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_CRM_ROTA_DURAK_GOREV'
      AND object_id = OBJECT_ID(N'dbo.CRM_ROTA_PLAN_DURAK'))
    CREATE INDEX IX_CRM_ROTA_DURAK_GOREV ON dbo.CRM_ROTA_PLAN_DURAK (GOREV_ID)
    WHERE GOREV_ID IS NOT NULL;
END;
GO

/* --- CRM_AKTIVITE: rota kaynagi (gorev silme / izleme) --- */
IF OBJECT_ID(N'dbo.CRM_AKTIVITE', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.CRM_AKTIVITE', 'ROTA_ID') IS NULL
    ALTER TABLE dbo.CRM_AKTIVITE ADD ROTA_ID BIGINT NULL;
  IF COL_LENGTH('dbo.CRM_AKTIVITE', 'ROTA_DURAK_ID') IS NULL
    ALTER TABLE dbo.CRM_AKTIVITE ADD ROTA_DURAK_ID BIGINT NULL;

  IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = N'IX_CRM_AKT_ROTA'
      AND object_id = OBJECT_ID(N'dbo.CRM_AKTIVITE'))
    CREATE INDEX IX_CRM_AKT_ROTA ON dbo.CRM_AKTIVITE (ROTA_ID, ROTA_DURAK_ID)
    WHERE ROTA_ID IS NOT NULL;
END;
GO
