/*
  CRM surum 26 - Rota onayda gorev otomasyon ve zaman plani parametreleri.
  Veritabani: ASYA_ENTEGRE
  Idempotent: tekrar calistirilabilir.
*/

SET NOCOUNT ON;

IF OBJECT_ID(N'dbo.PARAMETRE', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.PARAMETRE', 'ROTA_ONAYDA_GOREV_OTO') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD ROTA_ONAYDA_GOREV_OTO INT NOT NULL
      CONSTRAINT DF_PARAM_ROTA_GOREV_OTO DEFAULT (1);

  IF COL_LENGTH('dbo.PARAMETRE', 'ROTA_GOREV_ZAMAN_MOD') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD ROTA_GOREV_ZAMAN_MOD INT NOT NULL
      CONSTRAINT DF_PARAM_ROTA_GOREV_ZM DEFAULT (0);

  IF COL_LENGTH('dbo.PARAMETRE', 'ROTA_GOREV_BAS_SAAT') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD ROTA_GOREV_BAS_SAAT VARCHAR(5) NULL
      CONSTRAINT DF_PARAM_ROTA_GOREV_BS DEFAULT ('09:00');

  IF COL_LENGTH('dbo.PARAMETRE', 'ROTA_GOREV_DURAK_DK') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD ROTA_GOREV_DURAK_DK INT NOT NULL
      CONSTRAINT DF_PARAM_ROTA_GOREV_DK DEFAULT (45);

  UPDATE dbo.PARAMETRE
  SET ROTA_GOREV_BAS_SAAT = '09:00'
  WHERE ROTA_GOREV_BAS_SAAT IS NULL OR LTRIM(RTRIM(ROTA_GOREV_BAS_SAAT)) = '';
END;
GO
