/*
  CRM surum 32 - Rota zaman plani kolonlari.
*/
IF OBJECT_ID(N'dbo.CRM_ROTA_PLAN', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'GOREV_ZIYARET_DK') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD GOREV_ZIYARET_DK INT NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'GOREV_MESAI_BAS_SAAT') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD GOREV_MESAI_BAS_SAAT VARCHAR(5) NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'GOREV_MESAI_BIT_SAAT') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD GOREV_MESAI_BIT_SAAT VARCHAR(5) NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'GOREV_HIZ_KMH') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD GOREV_HIZ_KMH INT NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN', 'ZAMAN_PLAN_UTC') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN ADD ZAMAN_PLAN_UTC DATETIME2(3) NULL;
END;

IF OBJECT_ID(N'dbo.CRM_ROTA_PLAN_DURAK', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN_DURAK', 'PLAN_BAS_ZAMAN') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK ADD PLAN_BAS_ZAMAN DATETIME2(3) NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN_DURAK', 'PLAN_BIT_ZAMAN') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK ADD PLAN_BIT_ZAMAN DATETIME2(3) NULL;
  IF COL_LENGTH('dbo.CRM_ROTA_PLAN_DURAK', 'PLAN_YOL_DK') IS NULL
    ALTER TABLE dbo.CRM_ROTA_PLAN_DURAK ADD PLAN_YOL_DK INT NULL;
END;

IF OBJECT_ID(N'dbo.PARAMETRE', N'U') IS NOT NULL
BEGIN
  IF COL_LENGTH('dbo.PARAMETRE', 'ROTA_GOREV_BIT_SAAT') IS NULL
    ALTER TABLE dbo.PARAMETRE ADD ROTA_GOREV_BIT_SAAT VARCHAR(5) NULL
      CONSTRAINT DF_PARAM_ROTA_GOREV_BS2 DEFAULT ('18:00');
  UPDATE dbo.PARAMETRE
  SET ROTA_GOREV_BIT_SAAT = '18:00'
  WHERE ROTA_GOREV_BIT_SAAT IS NULL OR LTRIM(RTRIM(ROTA_GOREV_BIT_SAAT)) = '';
END;
